//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NET1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucMonThi
    {
        public string MaMon { get; set; }
        public string TenMon { get; set; }
    }
}
