//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NET1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoThiSinh
    {
        public string SBD { get; set; }
        public string HoTenThiSinh { get; set; }
        public string MaLop { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
    
        public virtual DanhMucLopThi DanhMucLopThi { get; set; }
    }
}
